package ifneeded de1_vars 1.0 [list source [file join "./" vars.tcl]]
package ifneeded de1_binary 1.0 [list source [file join "./" binary.tcl]]
package ifneeded de1_bluetooth 1.0 [list source [file join "./" bluetooth.tcl]]
package ifneeded de1_comms 1.0 [list source [file join "./" de1_comms.tcl]]
package ifneeded de1_gui 1.0 [list source [file join "./" gui.tcl]]
package ifneeded de1_utils 1.0 [list source [file join "./" utils.tcl]]
package ifneeded de1_main 1.0 [list source [file join "./" main.tcl]]
package ifneeded de1_creatormain 1.0 [list source [file join "./" creatormain.tcl]]
package ifneeded de1_machine 1.0 [list source [file join "./" machine.tcl]]
package ifneeded de1_misc 1.0 [list source [file join "./" misc.tcl]]
package ifneeded de1_updater 1.0 [list source [file join "./" updater.tcl]]
package ifneeded de1_usb 1.0 [list source [file join "./" usb.tcl]]

