(heating) {fr (chauffe) de (Erhitzen) zh-hant (努力加熱中) zh-hans (加热中) es (calentamiento) it (riscaldamento) pt (aquecimento) kr {(가열 중)} jp {(加熱中, ヒーティング)} ar (heating) hu (melegítés) tr (ısınma) th (heating) sv (uppvärmning) hu (melegítés) da (opvarmer) fi { (kuumennus)} ro (încălzire) hi (heating) pl (grzanie) no (heating) sk (ohrievanie) gr (ζέσταμα)}
{1: preinfuse} {fr {1: préinfusion} de {1: Vorinfusion} zh-hant １：預浸 zh-hans １：预浸 es {1: preinfusión} it {1: preinfusione} pt {1: preinfusão} kr {1: 프리인퓨전} jp 1:プリインフュージョン ar {1: preinfuse} hu {1: előáztatás} tr {1: preinfüzyon} th {1: พรมน้ำ} sv {1: preinfusera} hu {1: előáztatás} da {1: preinfuser} fi {1: esikuumenns} ro {1: preinfuzie} hi {1: preinfuse} pl 1:preinfuzja no {1: preinfuse} sk {1: predinfúzia} gr {1: προ-έγχυση}}
{2: hold} {fr {2: maintien} de {2: Halten} zh-hant ２：持續 zh-hans ２：持续 es {2: mantener} it {2: mantenimento} pt {2: manter} kr {2: 유지} jp ２：ホールド ar {2: hold} hu {2: tartás} tr {2: sabit} th {2: แรงดันคงที่} sv {2: upprätthåll} hu {2: tartás} da {2: oprethold} fi {2: ylläpidä} ro {2: menținere} hi {2: hold} pl {2:podtrzymanie ciśnienia} no {2: hold} sk {2: stabilný tlak} gr {2: κράτηση}}
{3: decline} {fr {3: déclin} de {3: Abnahme} zh-hant ３：降壓 zh-hans ３：降压 es {3: descenso} it {3: diminuzione} pt {3: redução} kr {3: 감소} jp 3:減少 ar {3: decline} hu {3: nyomás csökkentés} tr {3: düşüş} th {3: ลดแรงดัน} sv {3: reducera} hu {3: nyomás csökkentés} da {3: reducer} fi {3: vähennä} ro {3: reducere presiune} hi {3: decline} pl {3:redukcja ciśnienia} no {3: decline} sk {3: pokles tlaku} gr {3: ελάττωση}}
App: {fr App: de App: zh-hant 主程式： zh-hans 主程式： es App: it App: pt App: kr 어플리케이션: jp アプリケーション ar App: hu Alkalmazás: tr uygulama th แอพ: sv App: hu Alkalmazás: da App: fi App: ro Aplicație: hi App: pl Aplikacja: no App: sk Aplikácia: gr Εφαρμογή}
{Auto off:} {fr {Arrêt dans:} de {Abschaltung in:} zh-hant 自動停止： zh-hans 自动停止： es {Apagado en:} it {Spegni dopo:} pt {Desligamento em:} kr {자동 Off} jp 自動オフ ar {Auto off:} hu {Automatikus kikapcsolás:} tr {Oto kapanma:} th หยุดอัตโนมัติ: sv {Automatisk avstängning:} hu {Automatikus kikapcsolás:} da {Auto sluk:} fi {Automaattinen lopetus} ro {Oprire Automată:} hi {Auto off:} pl {wyłącznik zegarowy} no {Auto off:} sk {Automatické vypnutie:} gr {Αυτόματη απενεργοποίηση}}
awake {fr réveil de Aufwachen zh-hant 起動 zh-hans 起动 es reinicio it riattiva pt reactivação kr {대기모드 해제} jp 待機モードㅏ解除 ar awake hu ébrenlét tr Uyandırma th ตื่น sv vaken hu ébrenlét da vågen fi Päällä ro reactivare hi awake pl wzbudzono no awake sk aktívne gr ενεργό}
bar {fr bars de Bar zh-hant 巴 zh-hans 巴 es bar it bar pt bars kr bar jp 圧力(bar) ar bar hu bar tr bar th บาร์ sv bar hu bar da bar fi bar ro bar hi bar pl bar no bar sk bar gr {bar }}
Brightness {fr Luminosité de Helligkeit zh-hant 光亮度 zh-hans 光亮度 es Luminosidad it Luminosità pt Luminosidade kr {화면 밝기} jp 明るさ ar Brightness hu Fényerő tr Parlaklık th ความสว่าง sv Ljusstyrka hu Fényerő da Lysstyrke fi Kirkkaus ro luminozitate hi Brightness pl {Jasność ekranu} no Brightness sk Jas gr Φωτεινότητα}
Cancel {fr Annuler de Abbrechen zh-hant 取消 zh-hans 取消 es Cancelar it Annulla pt Anular kr 취소 jp 取り消し ar Cancel hu Mégsem tr İptal th ยกเลิก sv Avbryt hu Mégsem da Afbryd fi Peruuta ro Anulare hi Cancel pl Anuluj no Cancel sk Zrušiť gr Ακύρωση}
{Change after:} {fr {Changer après:} de {Ändern nach:} zh-hant 變更：每 zh-hans 变更：每 es {Cambiar despues de:} it {Cambia dopo:} pt {Alterar após:} kr { : 후 화면보호기 진입} jp ：後スクリーンセーバーに変更 ar {Change after:} hu {Váltás sűrűsége:} tr {Değiştirme süresi:} th เปลี่ยนหลังจาก: sv {Ändra efter:} hu {Váltás sűrűsége:} da {Skift efter:} fi {Muuta jälkeen:} ro {Schimbare după:} hi {Change after:} pl {Zmień obraz po:} no {Change after:} sk {Zmeniť po:} gr {Αλλαγή μετά από:}}
Clean {fr Nettoyer de Reinigen zh-hant 清洗 zh-hans 清洗 es Limpiar it Pulizia pt Limpar kr 청소하기 jp 掃除 ar Clean hu Tisztítás tr Temizleme th ทำความสะอาด sv Rengöring hu Tisztítás da Rengør fi Puhdistus ro Curățare hi Clean pl Wyczyść no Clean sk Vyčistiť gr Καθαρισμός}
Connect {fr {Se connecter} de {Verbindung herstellen} zh-hant 連接主機 zh-hans 连接主机 es Conectar it Connetti pt Conectar kr 연결하기 jp 連結する ar Connect hu Kapcsolódás tr Bağlan th เชื่อมต่อ sv {Koppla upp} hu Kapcsolódás da Forbind fi Yhdistä ro Conectare hi Connect pl Połącz no Connect sk Pripojiť gr Συνδέσου}
Connection {fr Connexion de Verbindung zh-hant 連接資訊 zh-hans 连接资讯 es Conexión it Connessione pt Conexão kr 연결 jp 連結 ar Connection hu Kapcsolat tr Bağlantı th การเชื่อมต่อ sv {Uppkopplad enhet} hu Kapcsolat da Forbindelse fi Yhteys ro Conexiune hi Connection pl Połączenie no Connection sk Pripojenie gr Σύνδεση}
Elapsed: {fr Écoulé: de Verstrichen: zh-hant 已運行： zh-hans 已运行： es Transcurridos: it Transcorsi: pt Decorrido: kr {경과 시간:} jp 経過時間 ar Elapsed: hu {Eltelt idő:} tr {Geçen süre:} th เวลาที่กำหนด: sv Förlopp: hu {Eltelt idő:} da Forløbet: fi Kulunut ro {Timp expirat} hi Elapsed: pl Upłynęlo no Elapsed: sk Uplynulo: gr {Παρερχόμενος χρόνος}}
Enable {fr Activer de Aktivieren zh-hant 使用 zh-hans 使用 es Activar it Attiva pt Activar kr 활성화 jp 活性化 ar Enable hu Engedélyezés tr Aktif th เปิด sv Aktivera hu Engedélyezés da Aktiver fi Aktivoi ro Activare hi Enable pl aktywne no Enable sk Aktivuj gr Ενεργοποίηση}
ESPRESSO {fr EXPRESSO de ESPRESSO es ESPRESSO it ESPRESSO pt EXPRESSO zh-hans 特浓咖啡 zh-hant 特濃咖啡 kr 에스프레소 jp エスプレッソ ar ESPRESSO hu ESZPRESSZÓ tr ESPRESSO th เอสเพรสโซ่ sv ESPRESSO hu ESZPRESSZÓ da ESPRESSO fi ESPROSSO ro ESPRESSO hi ESPRESSO pl ESPRESSO no ESPRESSO sk ESPRESSO gr ESPRESSO}
Espresso {fr {Circuit café} de Espresso zh-hant 咖啡部分 zh-hans 咖啡冲泡头 es Espresso it Espresso pt Expresso kr 에스프레소 jp エスプレッソ ar Espresso hu Eszpresszó tr Espresso th เอสเพรสโซ่ sv Espresso hu Eszpresszó da Espresso fi Espresso ro Espresso hi Espresso pl Espresso no Espresso sk Espresso gr Espresso}
espresso {fr expresso de espresso zh-hant 特濃咖啡 zh-hans 特浓咖啡 es espresso it espresso pt expresso kr 에스프레소 jp エスプレッソ ar espresso hu eszpresszó tr espresso th เอสเพรสโซ่ sv espresso hu eszpresszó da espresso fi espresso ro espresso hi espresso pl espresso no espresso sk espresso gr espresso}
Firmware {fr Firmware de Firmware zh-hant 韌體 zh-hans 韧体 es Firmware it Firmware pt Firmware kr 펌웨어 jp ファームウェア ar Firmware hu Firmware tr Firmware th เฟิร์มแวร์ sv Firmware hu Firmware da Firmware fi Laiteohjelmisto ro Firmware hi Firmware pl Oprogramowanie no Firmware sk Firmware gr Firmware}
{Going to sleep} {fr {Mise en veille} de {In Ruhezustand versetzen} zh-hant 進入休眠 zh-hans 进入休眠 es {Poner en suspensión} it {Modalità sospensione} pt {Colocaçao em modo de vigília} kr 절전모드 jp 節電モード ar {Going to sleep} hu {Alvó üzemmód} tr {Uykuya geçiyor} th {Going to sleep} sv {Går ner i viloläge} hu {Alvó üzemmód} da {Går i dvale} fi {Menossa lepotilaan} ro {Intare în mod veghe} hi {Going to sleep} pl Usypianie no {Going to sleep} sk Zaspávanie gr Αποκοίμηση}
Heated: {fr Chauffé: de Aufgeheizt: zh-hant 加熱完成： zh-hans 加热完成： es Calentado: it Pronto pt Aquecido: kr {:로 가열 완료} jp 加熱完了： ar Heated: hu Felmelegítve: tr Isıtıldı: th Heated: sv Klar: hu Felmelegítve: da Klar: fi Valmis ro Încălzit hi Heated: pl Gotowe no Heated: sk Zohriate: gr Ετοιμο:}
{HOT WATER} {fr {EAU CHAUDE} de HEISSWASSER es {AGUA CALIENTE} it {ACQUA CALDA} pt {ÁGUA QUENTE} zh-hans 热水 zh-hant 熱水 kr 온수 jp お湯 ar {HOT WATER} hu {FORRÓ VÍZ} tr {SICAK SU} th น้ำร้อน sv VARMVATTEN hu {FORRÓ VÍZ} da {VARMT VAND} fi {KUUMA VESI} ro {APĂ CALDĂ} hi {HOT WATER} pl {GORĄCA WODA} no {HOT WATER} sk {HORÚCA VODA} gr {ΖΕΣΤΟ ΝΕΡΟ}}
{Hot water} {fr {Eau chaude} de Heisswasser es {Agua caliente} it {Acqua calda} pt {Água quente} zh-hant 熱水溫度 zh-hans 热水温度 kr 온수 jp お湯温度 ar {Hot water} hu {Forró víz} tr {Sıcak su} th น้ำร้อน sv Varmvatten hu {Forró víz} da {Varmt vand} fi {Kuuma vesi} ro {Apă caldă} hi {Hot water} pl {Gorąca woda} no {Hot water} sk {Horúca voda} gr {Ζεστό Νερό}}
Information {fr Informations de Informationen zh-hant 主機資料 zh-hans 主机资料 es Información it Informazioni pt Informação kr 정보 jp インフォメーション ar Information hu Információ tr Bilgi th ข้อมูล sv Information hu Információ da Information fi Tietoja ro Infomații hi Information pl Informacje no Information sk Informácie gr Πληροφορίες}
MACHINE {fr MACHINE de MASCHINE zh-hant 主機 zh-hans 主机 es EQUIPO it MACCHINA pt MÁQUINA kr 머신 jp マシン ar MACHINE hu GÉP tr MAKİNE th MACHINE sv MASKIN hu GÉP da MASKINE fi KEITIN ro Aparat hi MACHINE pl Ekspres no MACHINE sk ZARIADENIE gr ΜΗΧΑΝΗ}
Measurements {fr Unités de Messungen zh-hant 數值單位 zh-hans 数值单位 es {Unidades de medida} it Parametri pt Mensurações kr {표시 단위 변경} jp 単位変更 ar Measurements hu Mértékegységek tr {Ölçü birimleri} th หน่วยวัด sv Mått hu Mértékegységek da Enhedder fi Mitat ro {Unități de măsură} hi Measurements pl Wskaźniki no Measurements sk Jednotky gr Μετρήσεις}
minutes {fr minutes de Minuten zh-hant 分鐘 zh-hans 分钟 es minutos it minuti pt minutos kr 분 jp 分 ar minutes hu perc tr dakika th นาที sv minuter hu perc da minutter fi Minuuttia ro minute hi minutes pl minuty no minutes sk minút gr λεπτά}
{Name your machine} {fr {Nommez votre machine} de {Geben Sie Ihrer Maschine einen Namen} zh-hant 主機名稱 zh-hans 主机名称 es {Nombre del equipo} it {Dai un nome alla tua macchina} pt {Nomeie seu máquina} kr {머신 이름 설정} jp マシン名前設定 ar {Name your machine} hu {Nevezd el a gépedet} tr {Makineyi isimlendir} th ชื่อเครื่องของคุณ sv {Namnge din maskin} hu {Nevezd el a gépedet} da {Navngiv din maskine} fi {Anna laitteelle nimi} ro {Dă un nume aparatului } hi {Name your machine} pl {Nazwij swoje urządzenie} no {Name your machine} sk {Pomenuj svoje zariadenie} gr {Ονόμα μηχάνής}}
Ok {fr OK de Ok zh-hant 確定 zh-hans 确定 es ok it Ok pt Ok kr 저장 jp 確定 ar Ok hu Ok tr Ok th ตกลง sv Ok hu Ok da Ok fi Ok ro Ok hi Ok pl {Zapisz zmiany} no Ok sk Ok gr OK}
OTHER {fr DIVERS de ANDERE zh-hant 其他 zh-hans 其他 es OTROS it ALTRO pt OUTRO kr 기타 jp その他 ar OTHER hu EGYÉB tr DİĞER th อื่นๆ sv ÖVRIGT hu EGYÉB da ANDET fi MUUT ro ALTELE hi OTHER pl INNE no OTHER sk INÉ gr ΑΛΛΑ}
{Please quit and restart this app to apply your changes.} {fr {Veuillez quitter et redémarrer cette app pour que les changements puissent prendre effet.} de {Bitte beenden und App neu starten, damit die Änderungen wirksam werden können.} zh-hant 請重啟本程式來套用新設定。 zh-hans 请重启本程式来套用新的设定。 es {Por favor, cierre y reinicie la aplicación para guardar las modificaciones.} it {Per favore, esci e riavvia l'app per applicare le modifiche} pt {Por favor, encerre e reinicie o programa para aplicar as suas alterações.} kr {변경사항을 적용하기 위해 어플리케이션을 재시작하세요.} jp 変更を承認した後、アプリケーションを再起動してください。 ar {Please quit and restart this app to apply your changes.} hu {Kérlek, lépj ki és indítsd újra az alkalmazást} tr {Değişikliklerin uygulanması için lütfen çıkış yapın ve uygulamayı yeniden başlatın.} th {ออกและเริ่มแอพใหม่ เพื่อเปลี่ยนการตั้งค่า} sv {Vänligen stäng och starta applikationen för att aktivera förändringarna} hu {Kérlek, lépj ki és indítsd újra az alkalmazást} da {Venligst afslut og genstart denne app for at aktivere dine ændringer} fi {Ole hyvä ja sulje ja käynnistä uudelleen} ro {Vă rog să ieșiți și să reporniți aplicația să se valideze modificările} hi {Please quit and restart this app to apply your changes.} pl {Proszę zrestartować aplikację aby wprowadzić zmiany.} no {Please quit and restart this app to apply your changes.} sk {Prosím reštartovať aplikáciu pre aktiváciu zmien.} gr {Κλείσε και επανεκκίνησε τη μηχάνή σου}}
{Power off} {fr Éteindre de Ausschalten zh-hant 關機時間 zh-hans 关机时间 es Apagado it Spegnimento pt Desligar kr {꺼짐 예약} jp 電源オフ予約 ar {Power off} hu Kikapcsolás tr Kapat th เวลาปิด sv Av hu Kikapcsolás da Sluk fi Sulje ro Oprit hi {Power off} pl Wyłącz no {Power off} sk Vypnúť gr {Απενεργοποίηση μηχανής}}
{Power on} {fr Allumer de Einschalten es Encender it Accendi pt Ligar zh-hant 開機時間 zh-hans 开机时间 kr {켜짐 예약} jp 電源オン ar {Power on} hu Bekapcsolás tr Aç th เปิด sv Start hu Bekapcsolás da Tænd fi {Virta päälle} ro Pornit hi {Power on} pl {Zasilanie włączone} no {Power on} sk Zapnuté gr Ενεργοποίηση}
PRESETS {fr PRÉRÉGLAGES de VOREINSTELLUNGEN zh-hant 預設 zh-hans 预设 es PREAJUSTES it {Opzioni predefinite} pt PREDEFINIÇÕES kr {사전 설정} jp 事前設定 ar PRESETS hu BEÁLLÍTÁSOK tr {ÖN AYARLAR} th PRESETS sv Inställningar hu BEÁLLÍTÁSOK da FORUDINDSTILLINGER fi Esiasetukset ro SETĂRI hi PRESETS pl NASTAWY no PRESETS sk Prednastavenia gr ΠΡΟΕΠΙΛΟΓΕΣ}
{pressure (bar)} {fr {pression (bars)} de {Druck (Bar)} zh-hant 壓力(巴數) zh-hans 压力(巴数值) es {presión (bar)} it {pressione (bar)} pt {pressão (bar)} kr {압력 (bar)} jp 圧力(bar) ar {pressure (bar)} hu {nyomás (bar)} tr {basınç (bar)} th {แรงดัน (บาร์)} sv {tryck (bar)} hu {nyomás (bar)} da {tryk (bar)} fi {Paine (bar)} ro {presiune (bar)} hi {pressure (bar)} pl {ciśnienie [bar]} no {pressure (bar)} sk {tlak (bar)} gr {Πίεση (bar)}}
{Pressure profiles} {fr {Profils de pression} de Druckprofile zh-hant 壓力預設檔 zh-hans 压力预设存档 es {Perfil de presión} it {Profili di pressione} pt {Perfis de pressão} kr {압력 프로파일} jp 圧力プロファイル ar {Pressure profiles} hu Nyomásprofilok tr {Basınç profilleri} th {Pressure profiles} sv Tryckprofiler hu Nyomásprofilok da {Tryk profiler} fi Paineprofiilit ro {Profil presiune} hi {Pressure profiles} pl {Profile ciśnienia} no {Pressure profiles} sk {Tlakové profily} gr {Προφίλ πίεσης}}
PRESSURE {fr PRESSION de DRUCK zh-hant 壓力 zh-hans 压力 es PRESIÓN it PRESSIONE pt PRESSÃO kr 압력 jp 圧力(bar) ar PRESSURE hu NYOMÁS tr BASINÇ th แรงดัน sv TRYCK hu NYOMÁS da TRYK fi PAINE ro PRESIUNE hi PRESSURE pl CIŚNIENIE no PRESSURE sk TLAK gr ΠΙΕΣΗ}
Pressure: {fr Pression: de Druck: zh-hant 壓力： zh-hans 压力： es Presión: it Pressione: pt Pressão: kr 압력: jp 圧力(bar) ar Pressure: hu Nyomás: tr Basınç: th แรงดัน: sv Tryck: hu Nyomás: da Tryk: fi Paine ro Presiune: hi Pressure: pl Ciśnienie: no Pressure: sk Tlak: gr Πίεση:}
Quit {fr Quitter de Beenden zh-hant 離開 zh-hans 离开 es Cerrar it Esci pt Encerrar kr 나가기 jp 終了 ar Quit hu Kilép tr Çıkış th ออก sv Avsluta hu Kilép da Afslut fi Lopeta ro Ieșire hi Quit pl Wyjście no Quit sk Ukončiť gr Ακύρωση}
Reset {fr Réinitialiser de Zurücksetzen zh-hant 重設 zh-hans 重设 es Reiniciar it Ripristino pt Redefinir kr {펌웨어 초기화} jp 再設定（リセット） ar Reset hu Visszaállítás tr Sıfırla th รีเซท sv {Starta om} hu Visszaállítás da Nulstil fi {Käynnistä uudelleen} ro Resetare hi Reset pl {Ustaw ponownie} no Reset sk Reset gr Επαναφορά}
Save {fr Sauvegarder de Speichern zh-hant 儲存 zh-hans 储存 es Guardar it Salva pt Salvar kr 저장 jp 保存 ar Save hu Mentés tr Kaydet th บันทึก sv Spara hu Mentés da Gem fi Tallenna ro Salvat hi Save pl Zapisz no Save sk Uložiť gr Αποθηκεύση}
save {fr sauvegarder de speichern zh-hant 儲存 zh-hans 储存 es guardar it salva pt salvar kr 저장 jp 保存 ar save hu mentés tr kaydet th บันทึก sv spara hu mentés da gem fi tallenna ro salvat hi save pl zapisz no save sk uložiť gr αποθηκεύση}
{Screen Saver} {fr {Écran de veille} de Bildschirmschoner zh-hant 屏幕保護 zh-hans 屏幕保护 es Salvapantallas it Salvaschermo pt {Protecção de Ecrã} kr 화면보호기 jp スクリーンセーバー ar {Screen Saver} hu Képernyőkímélő tr {Ekran Koruyucu} th พักหน้าจอ sv Skärmsläckare hu Képernyőkímélő da Pauseskærm fi Näytönsäästäjä ro {Economizor ecran} hi {Screen Saver} pl {Stan Uśpienia} no {Screen Saver} sk {Šetrič obrazovky} gr {Προστασία Οθόνης}}
{Screen saver:} {fr {Écran de veille:} de Bildschirmschoner: zh-hant 屏幕保護： zh-hans 屏幕保护： es Salvapantallas it Salvaschermo pt {Protecção de ecrã} kr 화면보호기: jp スクリーンセーバー ar {Screen saver:} hu Képernyőkímélő: tr {Ekran koruyucu:} th พักหน้าจอ: sv Skärmsläckare: hu Képernyőkímélő: da Pauseskærm: fi Näytönsäästäjä ro {Economizor ecran:} hi {Screen saver:} pl {Stan Uśpienia:} no {Screen saver:} sk {Šetrič obrazovky:} gr {Προστασία οθόνης:}}
seconds {fr secondes de Sekunden zh-hant 秒 zh-hans 秒 es segundos it secondi pt segundos kr 초 jp 秒 ar seconds hu másodperc tr saniye th วินาที sv sekunder hu másodperc da sekunder fi sekuntia ro secunde hi seconds pl sekundy no seconds sk sekúnd gr seconds}
{Serial number:} {fr {Numéro de série:} de Seriennummer: zh-hant 序號 zh-hans 序号 es {Número de serie:} it {Numero di serie:} pt {Número de série:} kr {시리얼 넘버} jp シリアルナンバー ar {Serial number:} hu Sorozatszám: tr {Seri numara:} th หมายเลขเครื่อง: sv Serienummer: hu Sorozatszám: da Serienummer: fi Sarjanumero ro {Număr serie} hi {Serial number:} pl {Numer seryjny:} no {Serial number:} sk {Sériové číslo:} gr {Σειριακός αριθμός}}
settings {fr paramètres de Einstellungen zh-hant 設定 zh-hans 设定 es Configuración it impostazioni pt configurações kr 설정 jp 設定 ar settings hu beállítások tr ayarlar th ตั้งค่า sv inställningar hu beállítások da indstillinger fi Asetukset ro setări hi settings pl ustawienia no settings sk nastavenia gr Ρυθμίσεις}
sleep {fr veille de Standby zh-hant 休眠 zh-hans 休眠 es suspender it sospensione pt vigília kr 대기모드 jp 待機モード ar sleep hu {alvó üzemmód} tr uyku th หลัก sv vila hu {alvó üzemmód} da dvale fi Lepotila ro {mod de veghe} hi sleep pl uśpienie no sleep sk {Režim spánku} gr Αποκοίμηση}
{Start after:} {fr {Démarrage après:} de {Start nach:} zh-hant 進入休眠：靜止 zh-hans 进入休眠：呆机 es {Empezar despues de:} it {Inizia dopo: } pt {Iniciar após:} kr {절전모드 진입:} jp 節電モード開始： ar {Start after:} hu Indítás: tr {Başlama süresi:} th {เริ่มหลังจาก :} sv {Starta efter:} hu Indítás: da {Start efter:} fi {Käynnistä jälkeen} ro {Pornire după:} hi {Start after:} pl {Włącz po:} no {Start after:} sk {Zapnúť po:} gr {Αρχίστε μετά απο:}}
start {fr démarrage de Start zh-hant 開始 zh-hans 开始 es comienzo it {Inizia dopo: } pt início kr 시작 jp スタート ar start hu indítás tr başlat th เริ่ม sv starta hu indítás da start fi käynnistä ro pornit hi start pl włącz no start sk zapnúť gr αρχή}
Steam: {fr Vapeur: de Dampf: zh-hant 蒸汽： zh-hans 蒸汽： es Vapor: it Vapore: pt Vapor: kr 스팀: jp スチーム： ar Steam: hu Gőz: tr Buhar: th {ไอน้ำ :} sv Ånga: hu Gőz: da Damp: fi Höyry: ro Aburi: hi Steam: pl Para no Steam: sk Para: gr Ατμός:}
STEAM {fr VAPEUR de DAMPF es VAPOR it VAPORE pt VAPOR zh-hans 蒸汽 zh-hant 蒸汽 kr 스팀 jp スチーム ar STEAM hu GŐZ: tr BUHAR: th ไอน้ำ sv ÅNGA hu GŐZ: da DAMP fi HÖYRY: ro ABURI hi STEAM pl PARA no STEAM sk PARA gr ΑΤΜΟΣ}
steam {fr vapeur de Dampf zh-hant 蒸汽 zh-hans 蒸汽 es vapor it vapore pt vapor kr 스팀 jp スチーム ar steam hu gőz tr buhar th ไอน้ำ sv ånga hu gőz da damp fi höyry ro aburi hi steam pl para no steam sk para gr ατμός}
Steam {fr {Circuit vapeur} de Dampf zh-hant 蒸汽部分 zh-hans 蒸汽棒 es Vapor it Vapore pt Vapor kr 스팀 jp スチーム ar Steam hu Gőz tr Buhar th ไอน้ำ sv Ånga hu Gőz da Damp fi Höyry ro Aburi hi Steam pl Para no Steam sk Para gr Ατμός}
stop {fr arrêter de anhalten zh-hant 停止 zh-hans 停止 es parar it interrompi pt parar kr 멈춤 jp 中止 ar stop hu stop tr Durdur th หยุด sv stopp hu stop da stop fi pysäytä ro Oprit hi stop pl stop no stop sk stop gr STOP}
{Tablet styles} {fr {Styles d'interface} de Tablet-Layout zh-hant 板面風格 zh-hans 板面风格 es {Estilo de pantalla} it {Stili per il tablet} pt {Estilos para o tablet} kr {태블릿 스타일} jp タブレットスタイル ar {Tablet styles} hu {Tablet stílusok} tr {Tablet temaları} th {Tablet styles} sv Skärmteman hu {Tablet stílusok} da Skærmtemaer fi Tablettityylit ro {Moduri tabletă} hi {Tablet styles} pl {Zmiania motywu} no {Tablet styles} sk {Motívy tabletu} gr {Στυλ Ταμπλέτας Διασύνδεσης}}
Timer {fr Minuterie de {Timer } zh-hant 定時開關 zh-hans 定时开关 es Temporizador it Timer pt Temporizador kr {자동 on/off 설정} jp タイマー ar Timer hu Időzítő tr Zamanlayıcı th ตั้งเวลา sv Timer hu Időzítő da Timer fi Ajastin ro Temporizator hi Timer pl Timer: no Timer sk Časovač gr Χρονόμετρο}
Update {fr {Mise à jour} de Aktualisieren zh-hant 更新 zh-hans 更新 es Actualizar it Aggiorna pt Actualizar kr 업데이트 jp アップデート ar Update hu Frissítés tr Güncelleme th Update sv Uppdatera hu Frissítés da Opdater fi Päivitä ro Actualizare hi Update pl Uaktualnienie no Update sk Aktualizácia gr Ενημέρωση}
{Use AM/PM} {fr {Utiliser AM/PM} de {AM/PM verwenden} zh-hant 使用12小時制 zh-hans 使用12小时制 es {Usar AM/PM} it {Usa AM/PM} pt {Usar AM/PM} kr {AM/PM 사용} jp AM/PM使用 ar {Use AM/PM} hu {AM/PM használata} tr {AM/PM kullan} th {ใช้ AM/PM} sv {Använd AM/PM (12h)} hu {AM/PM használata} da {Anvend AM/PM} fi {Käytä 12 h / 24 h} ro {Folosire AM/PM} hi {Use AM/PM} pl {Używaj zegaru 12 godzinnego} no {Use AM/PM} sk {Použi 12/24 hodinový režim} gr {Χρησιμοποιήστε π.μ. / μ.μ.}}
{Use Fahrenheit} {fr {Utiliser Fahrenheit} de {Fahrenheit verwenden} zh-hant 使用華氏 zh-hans 使用华氏 es {Usar Fahrenheit} it {Usa Fahrenheit} pt {Usar Fahrenheit} kr {화씨 사용} jp 華氏使用 ar {Use Fahrenheit} hu {Fahrenheit használata} tr {Fahrenheit kullan} th {ใช้ ฟาเรนไฮต์} sv {Använd Fahrenheit} hu {Fahrenheit használata} da {Anvend Fahrenheit} fi {Käytä fahrenheit-asteikkoa} ro {Folosire Fahrenheit} hi {Use Fahrenheit} pl {Używaj skali Fahrenheita} no {Use Fahrenheit} sk {Použi stupne Fahrenheita} gr {Χρησιμοποιήστε Fahrenheit}}
Version: {fr Version: de {Version } zh-hant 版本： zh-hans 版本： es Versión: it Versione: pt Versão: kr 버전: jp バージョン ar Version: hu Verzió: tr Sürüm: th รุ่น: sv Version: hu Verzió: da Version: fi Versio: ro Versiune: hi Version: pl Wersja: no Version: sk Verzia: gr Eκδοχή}
Water: {fr Eau: de Wasser: zh-hant 水溫： zh-hans 水温： es Agua: it Acqua: pt Água: kr 물: jp 水： ar Water: hu Víz: tr Su: th น้ำ: sv Vatten: hu Víz: da Vand: fi Vesi: ro Apă: hi Water: pl Woda: no Water: sk Voda: gr Νερό:}
water {fr eau de Wasser zh-hant 水 zh-hans 水 es agua it acqua pt água kr 물 jp 水 ar water hu víz tr su th น้ำ sv vatten hu víz da vand fi vesi ro apă hi water pl woda no water sk voda gr νερό}
ending {fr conclusion de Ende zh-hant 完成中 zh-hans 完成中 es finalizando it conclusione pt completando kr 완료 jp 完了中 ar ending hu befejezés tr bitiş th ending sv avslutar hu befejezés da afslutning fi lopettamassa ro finalizare hi ending pl finalizacja no ending sk finalizácia gr τέλος}
waiting {fr attente de warten zh-hant 等待中 zh-hans 等待中 es esperando it attendi pt espera kr 대기중 jp 待機中 ar waiting hu várakozás tr bekliyor th รอ sv väntar hu várakozás da venter fi odottaa ro așteptare hi waiting pl Czekam no waiting sk čakám gr αναμονή}
{heating the water tank} {fr {Mise en chauffe de la chaudière} de {Erhitzen des Wasserbehälters} zh-hant 水源加熱中 zh-hans 白水加热中 es {calentando el depósito de agua} it {riscaldamento del serbatoio d'acqua} pt {aquecimento do tanque de água} kr {워터탱크 가열 중} jp タンクの水を加熱する中 ar {heating the water tank} hu {víztartály melegítése} tr {su tankı ısıtılıyor} th {heating the water tank} sv {värmer vattentanken} hu {víztartály melegítése} da {opvarmer vandtanken} fi {Kuumentaa vesisäiliötä} ro {incălzire boiler} hi {heating the water tank} pl {podgrzewam wodę w zasobniku} no {heating the water tank} sk {zohrievanie bojlera} gr {θέρμανση νερού}}
{final heating} {fr {Stabilisation de la température} de {letzte Erhitzung} zh-hant 控溫 zh-hans 控温 es {Estabilizando la temperatura} it {riscaldamento finale} pt {último aquecimento} kr {최종 가열 중} jp 最終加熱中 ar {final heating} hu {utolsó melegítés} tr {stabilizasyon ısıtması} th รักษาอุณหภูมิ sv {stabiliserar temperatur} hu {utolsó melegítés} da {stabiliserer temperatur} fi Loppukuumennus ro {incălzire finală} hi {final heating} pl {stabilizuję temperaturę} no {final heating} sk {stabilizácia teploty} gr {Tελική θερμοκρασία}}
{perfecting the mix} {fr {perfectionnement du mélange} de {Perfektionierung der Mischung} zh-hant 調節水溫中 zh-hans 调节水温中 es {perfeccionando la mezcla} it {il mix perfetto} pt {aperfeiçoa da mistura} kr {설정된 온도로 믹싱 중} jp セッティングした温度でミックスして調整中 ar {perfecting the mix} hu {keverék tökéletesítése} tr {mükemmel karışımı yakalama} th {perfecting the mix} sv {optimerar temperatur} hu {keverék tökéletesítése} da {optimerer blandingen} fi {Optimoi sekoituksen} ro {Încălzire finală} hi {perfecting the mix} pl {doskonalę temperaturę} no {perfecting the mix} sk {zdokonaľovanie teploty mixu} gr {Βελτιστοποίηση θερμοκρασίας}}
(Cooling): {fr (Refroidissement): de (Abkühlung): zh-hant (冷卻中)： zh-hans (冷却中)： es (Refrigeración): it (Raffreddamento): pt (Resfriamento): kr (쿨링): jp （クーリング） ar (Cooling): hu (Hűtés): tr (Soğutma): th (Cooling): sv (Kyler): hu (Hűtés): da (Afkøling): fi (Jäähdytys): ro (Răcire) hi (Cooling): pl (Chłodzenie) no (Cooling): sk (Chladenie): gr (ψύξη)}
{Power on} {fr Allumer de Einschalten es Encender it Accendi pt Ligar zh-hant 開機時間 zh-hans 开机时间 kr {켜짐 예약} jp 電源オン ar {Power on} hu Bekapcsolás tr Aç th เปิด sv Start hu Bekapcsolás da Tænd fi {Virta päälle} ro Pornit hi {Power on} pl {Zasilanie włączone} no {Power on} sk Zapnuté gr Ενεργοποίηση}
{Hot water} {fr {Eau chaude} de Heisswasser es {Agua caliente} it {Acqua calda} pt {Água quente} zh-hant 熱水溫度 zh-hans 热水温度 kr 온수 jp お湯温度 ar {Hot water} hu {Forró víz} tr {Sıcak su} th น้ำร้อน sv Varmvatten hu {Forró víz} da {Varmt vand} fi {Kuuma vesi} ro {Apă caldă} hi {Hot water} pl {Gorąca woda} no {Hot water} sk {Horúca voda} gr {Ζεστό Νερό}}
WATER {fr EAU de WASSER es AGUA it ACQUA pt ÁGUA zh-hant 水 zh-hans 水 kr 물 jp 水 ar WATER hu VÍZ tr SU th น้ำ sv VATTEN hu VÍZ da VAND fi VESI ro APĂ hi WATER pl WODA no WATER sk VODA gr ΝΕΡΟ}
SETTINGS {fr PARAMÈTRES de EINSTELLUNGEN es CONFIGURACIÓN it IMPOSTAZIONI pt CONFIGURAÇÕES zh-hant 設定 zh-hans 设定 kr 설정 jp 設定 ar SETTINGS hu BEÁLLÍTÁSOK tr AYARLAR th ตั้งค่า sv INSTÄLLNINGAR hu BEÁLLÍTÁSOK da INDSTILLINGER fi ASETUKSET ro SETĂRI hi SETTINGS pl USTAWIENIA no SETTINGS sk NASTAVENIA gr ΡΥΘΜΙΣΕΙΣ}
Water {fr Eau de Wasser zh-hant 水 zh-hans 水 es Agua it Acqua pt Água kr 물 jp 水 ar Water hu Víz tr Su th น้ำ sv Vatten hu Víz da Vand fi Vesi ro Apă hi Water pl Woda no Water sk Voda gr Νερό}
heating {fr chauffe de Erhitzung es Calentando it riscaldamento pt heating zh-hant 努力加熱中 zh-hans 加热中 kr 가열중 jp 加熱中 ar heating hu melegítés tr ısıtılıyor th ทำความร้อน sv värmer hu melegítés da opvamning fi Kuumentaa ro încălzire hi heating pl podgrzewanie no heating sk ohrievanie gr ζέσταμα}
stabilising {fr stabilisation de Stabilisierung es Estabilizando it stabilizzazione pt stabilising zh-hant 小心控溫中 zh-hans 控温中 kr {안정화 중} jp 安定化中 ar stabilising hu stabilizálás tr {stabilize ediliyor} th รักษาอุณหภูมิ sv stabiliserar hu stabilizálás da stabilisering fi Tasapainottaa ro stabilizare hi stabilising pl stabilzowanie no stabilising sk stabilizácia gr σταθεροποίηση}
preinfusion {fr préinfusion de Vorinfusion es Pre-infusión it preinfusione pt preinfusion zh-hant 輕輕預浸中 zh-hans 预浸中 kr 프리인퓨전 jp プリインフュージョン ar preinfusion hu előáztatás tr preinfüzyon th พรมน้ำ sv preinfusion hu előáztatás da preinfusion fi esikuumennus ro preinfuzie hi preinfusion pl preinfuzja no preinfusion sk predinfúzia gr προ-έγχυση}
pouring {fr extraction de Extraktion es Extrayendo it estrazione pt pouring zh-hant 快樂注水中 zh-hans 注水中 kr 추출중 jp 抽出中 ar pouring hu csapolás tr ekstraksiyon th สกัดกาแฟ sv extraherar hu csapolás da ekstraherer fi annostaa ro extracție hi pouring pl parzenie no pouring sk extrakcia gr εκχύλιση}
Saved {fr Sauvegardé de gespeichert es Guardado it Salvato pt Saved zh-hant 儲存成功 zh-hans 储存成功 kr 저장됨 jp 保存完了 ar Saved hu Elmentve tr Kaydedildi th บันทึก sv Sparad hu Elmentve da Gemt fi Tallennettu ro Salvat hi Saved pl Zapisano no Saved sk Uložené gr Αποθηκεύθηκε}
Pair {fr Jumeler de Koppeln es Vincular it Accoppia pt Pair zh-hant 連接主機 zh-hans 连接主机 kr 연결 jp 接続 ar Pair hu Párosítás tr eşitle th Pair sv {Para ihop} hu Párosítás da Parring fi Pair ro Pair hi Pair pl Paruj no Pair sk Párovať gr {Ζευγάρωμα Bluetooth}}
{Heat up} {fr Allumer de Aufheizen es Calentamiento it Riscaldamento pt {Heat up} zh-hant 開始熱身 zh-hans 开始加热 kr {켜짐 예약} jp ヒートアップ ar {Heat up} hu melegítés tr ısıt th {Heat up} sv Uppvärmning hu melegítés da Opvarmning fi {Heat up} ro {Heat up} hi {Heat up} pl Podgrzej no {Heat up} sk Zohriať gr Ζέσταμα}
{Cool down} {fr Éteindre de Abkühlen es Enfriamiento it Raffreddamento pt {Cool down} zh-hant 開始降溫 zh-hans 开始降温 kr {꺼짐 예약} jp クールダウン ar {Cool down} hu Hűtés tr soğut th {Cool down} sv Nerkylning hu Hűtés da Nedkøling fi {Cool down} ro {Cool down} hi {Cool down} pl Schłódź no {Cool down} sk Vychladiť gr Κλείσιμο}
Scheduler {fr Planificateur de Planer es Temporizador it Programmazione pt Scheduler zh-hant 定時操作 zh-hans 定时开关 kr {자동 on/off 설정} jp 自動電源設定 ar Scheduler hu Időzítő tr Scheduler th Scheduler sv Schemaläggning hu Időzítő da Planlægger fi Scheduler ro Scheduler hi Scheduler pl Harmonogram no Scheduler sk Plánovač gr Χρονοπρογραμματισμός}
{Screen Brightness} {fr {Screen Brightness} de Bildschirmhelligkeit es {Luminosidad de la pantalla} it {Luminosità dello schermo} pt {Screen Brightness} zh-hant 屏幕光亮度 zh-hans 屏幕光亮度 kr {화면 밝기} jp 画面の明るさ ar {Screen Brightness} hu Fényerő tr {ekran parlaklığı} th ความสว่างหน้าจอ sv {Skärmens ljusstyrka} hu Fényerő da Skærmlysstyrke fi {Screen Brightness} ro {Screen Brightness} hi {Screen Brightness} pl {Jasność Ekranu} no {Screen Brightness} sk {Jas obrazovky} gr {Φωτεινότητα Οθόνης}}
{Energy Saver} {fr {Économiseur d'énergie} de Energiesparer es {Ahorro de energía} it {Risparmio energetico} pt {Energy Saver} zh-hant 節能設定 zh-hans 节能设定 kr 절전모드 jp 節電モード ar {Energy Saver} hu {Energiatakarékos üzem} tr {enerji tasarrufu} th ประหยัดพลังงาน sv Energisparläge hu {Energiatakarékos üzem} da Energisparer fi {Energy Saver} ro {Energy Saver} hi {Energy Saver} pl {Tryb Oszczędzania Energii} no {Energy Saver} sk {Šetrič energie} gr {Εξοικονόμηση ενέργειας}}
{Available machines:} {fr {Machines disponibles:} de {Verfügbare Maschinen:} es {Equipos disponibles} it {Macchine disponibili} pt {Available machines:} zh-hant 可選主機 zh-hans 可选主机 kr {연결 가능한 머신:} jp 繋がれる機械： ar {Available machines:} hu {Rendelkezésre álló gépek} tr {uygun makina} th {Available machines:} sv {Tillgängliga enheter} hu {Rendelkezésre álló gépek} da {Tilgængelige maskiner} fi {Available machines:} ro {Available machines:} hi {Available machines:} pl {Dostępne urządzenia:} no {Available machines:} sk {Dostupné zariadenia:} gr {Διαθέσιμες μηχανές:}}
Fahrenheit {fr Fahrenheit de Fahrenheit es Fahrenheit it Fahrenheit pt Fahrenheit zh-hant 華氏 zh-hans 华氏 kr 화씨 jp 華氏 ar Fahrenheit hu Fahrenheit tr fahrenayt th ฟาห์เรนไฮต์ sv Fahrenheit​ hu Fahrenheit da Fahrenheit fi Fahrenheit ro Fahrenheit hi Fahrenheit pl Fahrenheit no Fahrenheit sk Fahrenheit gr Fahrenheit}
AM/PM {fr AM/PM de AM/PM es AM/PM it AM/PM pt AM/PM zh-hant 12小時制 zh-hans 12小时制 kr AM/PM jp AM/PM ar AM/PM hu AM/PM tr {gündüz/öğleden sonra} th AM/PM sv AM/PM hu AM/PM da AM/PM fi AM/PM ro AM/PM hi AM/PM pl AM/PM no AM/PM sk 12/24 gr {π.μ. / μ.μ.}}
1.234,56 {fr 1.234,56 de 1'234.56 es 1.234,56 it 1.234,56 pt 1.234,56 zh-hant 歐式標點 zh-hans 欧式标点 kr 1.234,56 jp 1.234,56 ar 1.234,56 hu 1.234,56 tr 1.234,55 th 1.234,56 sv 1.234,56 hu 1.234,56 da 1.234,56 fi 1.234,56 ro 1.234,56 hi 1.234,56 pl 1.234,56 no 1.234,56 sk 1.234,56 gr 1.234,56}
{Auto stop:} {fr {Arrêt auto.:} de {Automatische Abschaltung:} es {Auto stop} it {Spegnimento Automatico} pt {Auto stop:} zh-hant 自動停止： zh-hans 自动停止： kr {자동 정지} jp 自動停止 ar {Auto stop:} hu {Automatikus megállítás:} tr {otomatik dur} th หยุดอัตโนมัติ sv {Automatisk avstängning:} hu {Automatikus megállítás:} da {Auto stop:} fi {Auto stop:} ro {Auto stop:} hi {Auto stop:} pl {Auto stop:} no {Auto stop:} sk {Auto stop:} gr {Auto stop:}}
{Cool down after:} {fr {Éteindre après:} de {Abkühlen nach:} es {Enfriar después de:} it {Raffredda  dopo} pt {Cool down after:} zh-hant 降低溫度：如靜止 zh-hans 降低温度：如静止 kr {절전 상태로 전환:} jp 温度を冷やす ar {Cool down after:} hu {Hűtés időzítő:} tr {sonrasında soğut} th {Cool down after:} sv {Nedkylning efter:} hu {Hűtés időzítő:} da {Nedkøling efter:} fi {Cool down after:} ro {Cool down after:} hi {Cool down after:} pl {Wyłącz grzanie po:} no {Cool down after:} sk {Vychladiť po:} gr {Αποθέρμανση στα:}}
{Change every:} {fr {Changer chaque:} de {Ändern alle:} es {Cambiar cada:} it {Cambia ogni} pt {Change every:} zh-hant 變更圖像：每 zh-hans 变更图像：每 kr {화면보호기 슬라이드쇼:} jp ：後スクリーンセーバーに変更 ar {Change every:} hu {Váltás sűrűsége:} tr {herşeyi değiştir} th เปลี่ยนทุก: sv {Ändra varje:} hu {Váltás sűrűsége:} da {Aktiver efter:} fi {Change every:} ro {Change every:} hi {Change every:} pl {Zmień co} no {Change every:} sk {Zmeniť každých:} gr {Αλλαγή κάθε:}}
