(heating) {fr (chauffage) de (Erhitzen) zh-hant (加熱中) zh-hans (加热中) es (calentamiento) it (riscaldamento) pt (aquecimento) kr {(가열 중)} jp {(加熱中, ヒーティング)} ar (heating) hu (melegítés) tr (ısınma) th (heating) sv (uppvärmning) hu (melegítés) da (opvarmning) fi { (kuumennus)}}
{1: preinfuse} {fr {1: préinfusion} de {1: Vorinfusion} zh-hant １：預浸 zh-hans １：预浸 es {1: preinfusión} it {1: preinfusione} pt {1: preinfusão} kr {1: 프리인퓨전} jp 1:プリインフュージョン ar {1: preinfuse} hu {1: előáztatás} tr {1: preinfüzyon} th {1: preinfuse} sv {1: preinfusera} hu {1: előáztatás} da {1: preinfusion} fi {1: esikuumenns}}
{2: hold} {fr {2: maintien} de {2: Halten} zh-hant ２：持續 zh-hans ２：持续 es {2: mantener} it {2: mantenimento} pt {2: manter} kr {2: 유지} jp 2:ホールド ar {2: hold} hu {2: tartás} tr {2: sabit} th {2: hold} sv {2: upprätthåll} hu {2: tartás} da {2: hold} fi {2: ylläpidä}}
{3: decline} {fr {3: déclin} de {3: Abnahme} zh-hant ３：回落 zh-hans ３：回落 es {3: descenso} it {3: diminuzione} pt {3: redução} kr {3: 감소} jp 3:減少 ar {3: decline} hu {3: nyomás csökkentés} tr {3: düşüş} th {3: decline} sv {3: reducera} hu {3: nyomás csökkentés} da {3: reducer} fi {3: vähennä}}
App: {fr App: de App: zh-hant 主程式： zh-hans 主程式： es App: it App: pt App: kr 앱: jp App: ar App: hu Alkalmazás: tr App: th App: sv App: hu Alkalmazás: da App: fi App:}
{Auto off:} {fr {Arrêt dans:} de {Abschaltung in:} zh-hant 自動停止： zh-hans 自动停止： es {Apagado en:} it {Spegni dopo:} pt {Desligamento em:} kr {자동 Off} jp 自動オフ ar {Auto off:} hu {Automatikus kikapcsolás:} tr {Oto kapanma:} th {Auto off:} sv {Automatisk avstängning:} hu {Automatikus kikapcsolás:} da {Auto sluk:} fi {Automaattinen lopetus}}
awake {fr réveil de Aufwachen zh-hant 起動 zh-hans 起动 es reinicio it riattiva pt reactivação kr {대기모드 해제} jp 待機モードㅏ解除 ar awake hu ébrenlét tr Uyandırma th awake sv vaken hu ébrenlét da opvågne fi Päällä}
bar {fr bars de Bar zh-hant 巴 zh-hans 巴 es bares it bar pt bars kr 압력 jp 圧力 ar bar hu bar tr bar th บาร์ sv bar hu bar da bar fi bar}
Brightness {fr Luminosité de Helligkeit zh-hant 光亮度 zh-hans 光亮度 es Luminosidad it Luminosità pt Luminosidade kr 밝기 jp 明るさ ar Brightness hu Fényerő tr Parlaklık th ความสว่าง sv Ljusstyrka hu Fényerő da Lysstyrke fi Kirkkaus}
Cancel {fr Annuler de Abbrechen zh-hant 取消 zh-hans 取消 es Cancelar it Annulla pt Anular kr 취소 jp 取り消し ar Cancel hu Mégsem tr İptal th ยกเลิก sv Avbryt hu Mégsem da Afbryde fi Peruuta}
{Change after:} {fr {Changer après:} de {Ändern nach:} zh-hant 變更：每 zh-hans 变更：每 es {Cambiar despues de:} it {Cambia dopo:} pt {Alterar após:} kr {:분 후 변경} jp :分後変更 ar {Change after:} hu {Stílusváltás sűrűsége:} tr {Değiştirme süresi:} th {Change after:} sv {Ändra efter:} hu {Stílusváltás sűrűsége:} da {Skift efter} fi {Muuta jälkeen:}}
Clean {fr Nettoyer de Reinigen zh-hant 清洗 zh-hans 清洗 es Limpiar it Pulizia pt Limpar kr 청소하기 jp 掃除 ar Clean hu Tisztítás tr Temizleme th ทำความสะอาด sv Rengöring hu Tisztítás da Rengør fi Puhdistus}
Connect {fr {Se connecter} de {Verbindung herstellen} zh-hant 連接主機 zh-hans 连接主机 es Conectarse it Connetti pt Conectar kr 연결하기 jp コンタクトする ar Connect hu Kapcsolódás tr Bağlan th เชื่อมต่อ sv {Koppla upp} hu Kapcsolódás da Forbind fi Yhdistä}
Connection {fr Connexion de Verbindung zh-hant 連接資訊 zh-hans 连接资讯 es Conexión it Connessione pt Conexão kr 연결 jp コンタクト ar Connection hu Kapcsolat tr Bağlantı th การเชื่อมต่อ sv {Uppkopplad enhet} hu Kapcsolat da Forbindelse fi Yhteys}
Elapsed: {fr Écoulé: de Verstrichen: zh-hant 已運行： zh-hans 已运行： es Transcurridos: it Transcorsi: pt Decorrido: kr {경과 시간:} jp 経過 ar Elapsed: hu {Eltelt idő:} tr {Geçen süre:} th Elapsed: sv Åtgång: hu {Eltelt idő:} da Forløbet fi Kulunut}
Enable {fr Activer de Aktivieren zh-hant 使用 zh-hans 使用 es Activar it Attiva pt Activar kr 활성화 jp 活性化 ar Enable hu Enable tr Aktif th Enable sv Aktivera hu Enable da Aktiver fi Aktivoi}
ESPRESSO {fr EXPRESSO de ESPRESSO es ESPRESSO it ESPRESSO pt EXPRESSO zh-hans 特浓咖啡 zh-hant 特濃咖啡 kr 에스프레소 jp エスプレッソ ar ESPRESSO hu ESZPRESSZÓ tr ESPRESSO th เอสเพรสโซ่ sv ESPRESSO hu ESZPRESSZÓ da ESPRESSO fi ESPROSSO}
Espresso {fr Expresso de Espresso zh-hant 咖啡沖煮頭 zh-hans 咖啡冲泡头 es ESPRESSO it Espresso pt Expresso kr 에스프레소 jp エスプレッソ ar Espresso hu Eszpresszó tr Espresso th เอสเพรสโซ่ sv Espresso hu Eszpresszó da Espresso fi Espresso}
espresso {fr expresso de espresso zh-hant 特濃咖啡 zh-hans 特浓咖啡 es ESPRESSO it espresso pt expresso kr 에스프레소 jp エスプレッソ ar espresso hu eszpresszó tr espresso th เอสเพรสโซ่ sv espresso hu eszpresszó da espresso fi espresso}
Firmware {fr Firmware de Firmware zh-hant 韌體 zh-hans 韧体 es Firmware it Firmware pt Firmware kr 펌웨어 jp ファームウェア ar Firmware hu Firmware tr Firmware th Firmware sv Firmware hu Firmware da Firmware fi Laiteohjelmisto}
{Going to sleep} {fr {Mise en veille} de {In Ruhezustand versetzen} zh-hant 進入休眠 zh-hans 进入休眠 es {Poner en suspensión} it {Modalità sospensione} pt {Colocaçao em modo de vigília} kr 절전모드 jp 節電モード ar {Going to sleep} hu {Alvó üzemmód} tr {Uykuya geçiyor} th {Going to sleep} sv {Går ner i viloläge} hu {Alvó üzemmód} da {Går i dvale} fi {Menossa lepotilaan}}
Heated: {fr Chauffé: de Aufgeheizt: zh-hant 加熱完成： zh-hans 加热完成： es Calentado: it Pronto pt Aquecido: kr {:로 가열 완료} jp 加熱 ar Heated: hu Felmelegítve: tr Isıtıldı: th Heated: sv Klar: hu Felmelegítve: da Klar: fi Valmis}
{HOT WATER} {fr {EAU CHAUDE} de HEISSWASSER es {AGUA CALIENTE} it {ACQUA CALDA} pt {ÁGUA QUENTE} zh-hans 热水 zh-hant 熱水 kr 온수 jp お湯 ar {HOT WATER} hu {FORRÓ VÍZ} tr {SICAK SU} th น้ำร้อน sv {VARMT VATTEN} hu {FORRÓ VÍZ} da {VARMT VAND} fi {KUUMA VESI}}
{Hot water} {fr {Eau chaude} de Heisswasser es {Agua caliente} it {Acqua calda} pt {Água quente} zh-hant 熱水溫度 zh-hans 热水温度 kr 온수 jp お湯 ar {Hot water} hu {Forró víz} tr {Sıcak su} th น้ำร้อน sv Varmvatten hu {Forró víz} da {Varmt vand} fi {Kuuma vesi}}
Information {fr Informations de Informationen zh-hant 主機資料 zh-hans 主机资料 es Informaciones it Informazioni pt Informação kr 정보 jp インフォメーション ar Information hu Információ tr Bilgi th ข้อมูล sv Information hu Információ da Information fi Tietoja}
MACHINE {fr MACHINE de MASCHINE zh-hant 主機 zh-hans 主机 es MÁQUINA it MACCHINA pt MÁQUINA kr 머신 jp マシン ar MACHINE hu GÉP tr MAKİNE th MACHINE sv MASKIN hu GÉP da MASKINE fi KEITIN}
Measurements {fr Mesures de Messungen zh-hant 數值單位 zh-hans 数值单位 es Mediciones it Parametri pt Mensurações kr {측정 단위 변경} jp 測定値 ar Measurements hu Mértékegységek tr {Ölçü birimleri} th Measurements sv Mått hu Mértékegységek da Målinger fi Mitat}
minutes {fr minutes de Minuten zh-hant 分鐘 zh-hans 分钟 es minutos it minuti pt minutos kr 분 jp 分 ar minutes hu perc tr dakika th นาที sv minuter hu perc da minutter fi Minuuttia}
{Name your machine} {fr {Nommez votre machine} de {Geben Sie Ihrer Maschine einen Namen} zh-hant 主機名稱 zh-hans 主机名称 es {Nombre su máquina} it {Dai un nome alla tua macchina} pt {Nomeie seu máquina} kr {머신 이름 설정} jp マシン名前設定 ar {Name your machine} hu {Nevezd el a gépedet} tr {Makineyi isimlendir} th ชื่อเครื่องของคุณ sv {Namnge din maskin} hu {Nevezd el a gépedet} da {Giv maskinen et navn} fi {Anna laitteelle nimi}}
Ok {fr OK de Ok zh-hant 確定 zh-hans 确定 es ok it Ok pt Ok kr 확인 jp オッケー ar Ok hu Ok tr Ok th ตกลง sv Ok hu Ok da Ok fi Ok}
OTHER {fr DIVERS de ANDERE zh-hant 其他 zh-hans 其他 es OTRO it ALTRO pt OUTRO kr 기타 jp その他 ar OTHER hu EGYÉB tr DİĞER th อื่นๆ sv ÖVRIGT hu EGYÉB da ANDRE fi MUUT}
{Please quit and restart this app to apply your changes.} {fr {Veuillez quitter et redémarrer cette app pour que les changements puissent prendre effet.} de {Bitte beenden und starten Sie diese App neu, damit die Änderungen wirksam werden können.} zh-hant 請重啟本程式來套用新設定。 zh-hans 请重启本程式来套用新的设定。 es {Por reinicie la aplicación para aplicar sus modificaciones.} it {Per favore, esci e riavvia l'app per applicare le modifiche} pt {Por favor, encerre e reinicie o programa para aplicar as suas alterações.} kr {변경사항을 적용하기 위해 어플리케이션을 재시작하세요.} jp 変更を承認した後、アプリケーションを再起動してください。 ar {Please quit and restart this app to apply your changes.} hu {Kérlek, lépj ki és indítsd újra az alkalmazást} tr {Değişikliklerin uygulanması için lütfen çıkış yapın ve uygulamayı yeniden başlatın.} th {Please quit and restart this app to apply your changes.} sv {Vänligen stäng och starta applikationen för att aktivera förändringarna} hu {Kérlek, lépj ki és indítsd újra az alkalmazást} da {Venligst afslut og genstart denne app for at aktivere dine ændringer} fi {Ole hyvä ja sulje ja käynnistä uudelleen}}
{Power off} {fr Éteindre de Ausschalten zh-hant 關機時間 zh-hans 关机时间 es Apagar it Spegnimento pt Desligar kr {꺼짐 예약} jp 電源オフ ar {Power off} hu Kikapcsolás tr Kapat th {Power off} sv Avstängning hu Kikapcsolás da Sluk fi Sulje}
{Power on} {fr Allumer de Einschalten es Encender it Accendi pt Ligar zh-hant 開機 zh-hans 开机 kr 전원 jp 電源オン ar {Power on} hu Bekapcsolás tr Aç th {Power on} sv Start hu Bekapcsolás da Tænd fi {Virta päälle}}
PRESETS {fr PRÉRÉGLAGES de VOREINSTELLUNGEN zh-hant 預設 zh-hans 预设 es PREESTABLECIDOS it {Opzioni predefinite} pt PREDEFINIÇÕES kr {사전 설정} jp 事前設定 ar PRESETS hu BEÁLLÍTÁSOK tr {ÖN AYARLAR} th PRESETS sv Inställningar hu BEÁLLÍTÁSOK da Forudindstillinger fi Esiasetukset}
{pressure (bar)} {fr {pression (bars)} de {Druck (Bar)} zh-hant 壓力(巴數) zh-hans 压力(巴数值) es {presión (bares)} it {pressione (bar)} pt {pressão (bar)} kr {압력 (bar)} jp 圧力(bar) ar {pressure (bar)} hu {nyomás (bar)} tr {basınç (bar)} th {แรงดัน (บาร์)} sv {tryck (bar)} hu {nyomás (bar)} da {tryk (bar)} fi {Paine (bar)}}
{Pressure profiles} {fr {Profils de pression} de Druckprofile zh-hant 壓力預設檔 zh-hans 压力预设存档 es {Perfiles de presión} it {Profili di pressione} pt {Perfis de pressão} kr {압력 프로파일} jp 圧力プロファイル ar {Pressure profiles} hu Nyomásprofilok tr {Basınç profilleri} th {Pressure profiles} sv Tryckprofiler hu Nyomásprofilok da {Tryk profiler} fi Paineprofiilit}
PRESSURE {fr PRESSION de DRUCK zh-hant 壓力 zh-hans 压力 es PRESIÓN it PRESSIONE pt PRESSÃO kr 압력 jp 圧力(bar) ar PRESSURE hu NYOMÁS tr BASINÇ th แรงดัน sv TRYCK hu NYOMÁS da TRYK fi PAINE}
Pressure: {fr Pression: de Druck: zh-hant 壓力： zh-hans 压力： es Presión: it Pressione: pt Pressão: kr 압력: jp 圧力(bar) ar Pressure: hu Nyomás: tr Basınç: th แรงดัน: sv Tryck: hu Nyomás: da Tryk: fi Paine}
Quit {fr Quitter de Beenden zh-hant 離開 zh-hans 离开 es Cerrar it Esci pt Encerrar kr 나가기 jp 終了 ar Quit hu Kilép tr Çıkış th ออก sv Avsluta hu Kilép da Afslut fi Lopeta}
Reset {fr Réinitialiser de Zurücksetzen zh-hant 重設 zh-hans 重设 es Reinicializar it Riavvia pt Redefinir kr 리셋 jp 再設定（リセット） ar Reset hu Visszaállítás tr Sıfırla th Reset sv {Starta om} hu Visszaállítás da Nulstil fi {Käynnistä uudelleen}}
Save {fr Sauvegarder de Speichern zh-hant 儲存 zh-hans 储存 es Guardar it Salva pt Salvar kr 저장 jp セーブ ar Save hu Mentés tr Kaydet th Save sv Spara hu Mentés da Gem fi Tallenna}
save {fr sauvegarder de speichern zh-hant 儲存 zh-hans 储存 es guardar it salva pt salvar kr 저장 jp セーブ ar save hu mentés tr kaydet th save sv spara hu mentés da gem fi tallenna}
{Screen Saver} {fr {Écran de veille} de Bildschirmschoner zh-hant 屏幕保護 zh-hans 屏幕保护 es Salvapantallas it Salvaschermo pt {Protecção de Ecrã} kr 화면보호기 jp スクリーンセーバー ar {Screen Saver} hu Képernyőkímélő tr {Ekran Koruyucu} th พักหน้าจอ sv Skärmsläckare hu Képernyőkímélő da Pauseskærm fi Näytönsäästäjä}
{Screen saver:} {fr {Écran de veille:} de Bildschirmschoner: zh-hant 屏幕保護： zh-hans 屏幕保护： es Salvapantallas it Salvaschermo pt {Protecção de ecrã} kr 화면보호기: jp スクリーンセーバー ar {Screen saver:} hu Képernyőkímélő: tr {Ekran koruyucu:} th พักหน้าจอ: sv Skärmsläckare: hu Képernyőkímélő: da Pauseskærm fi Näytönsäästäjä}
seconds {fr secondes de Sekunden zh-hant 秒 zh-hans 秒 es segundos it secondi pt segundos kr 초 jp 秒 ar seconds hu másodperc tr saniye th วินาที sv sekunder hu másodperc da sekunder fi sekuntia}
{Serial number:} {fr {Numéro de série:} de Seriennummer: zh-hant 序號 zh-hans 序号 es {Numéro de serie:} it {Numero di serie:} pt {Número de série:} kr {시리얼 넘버} jp シリアルナンバー ar {Serial number:} hu Sorozatszám: tr {Seri numara:} th {Serial number:} sv Serienummer: hu Sorozatszám: da Serienummer: fi Sarjanumero}
settings {fr paramètres de Einstellungen zh-hant 設定 zh-hans 设定 es configuración it impostazioni pt configurações kr 설정 jp 設定 ar settings hu beállítások tr ayarlar th ตั้งค่า sv inställningar hu beállítások da indstillinger fi Asetukset}
sleep {fr veille de Standby zh-hant 休眠 zh-hans 休眠 es suspensión it sospensione pt vigília kr 대기모드 jp 待機モード ar sleep hu {alvó üzemmód} tr uyku th sleep sv vila hu {alvó üzemmód} da dvale fi Lepotila}
{Start after:} {fr {Démarrage après:} de {Start nach:} zh-hant 進入休眠：靜止 zh-hans 进入休眠：呆机 es {Empezar despues de:} it {Inizia dopo: } pt {Iniciar após:} kr {:후 시작} jp ：後スタート ar {Start after:} hu {Start after:} tr {Başlama süresi:} th {Start after:} sv {Starta efter:} hu {Start after:} da {Start efter:} fi {Käynnistä jälkeen}}
start {fr démarrage de Start zh-hant 開始 zh-hans 开始 es empezar it {Inizia dopo: } pt início kr 시작 jp スタート ar start hu indítás tr başlat th เริ่ม sv starta hu indítás da start fi käynnistä}
Steam: {fr Vapeur: de Dampf: zh-hant 蒸汽： zh-hans 蒸汽： es Vapor: it Vapore: pt Vapor: kr 스팀: jp スチーム： ar Steam: hu Gőz: tr Buhar: th {ไอน้ำ :} sv Ånga: hu Gőz: da Damp: fi Höyry:}
STEAM {fr VAPEUR de DAMPF es VAPOR it VAPORE pt VAPOR zh-hans 蒸汽 zh-hant 蒸汽 kr 스팀 jp スチーム ar STEAM hu GŐZ: tr BUHAR: th ไอน้ำ sv ÅNGA hu GŐZ: da DAMP fi HÖYRY:}
steam {fr vapeur de Dampf zh-hant 蒸汽 zh-hans 蒸汽 es vapor it vapore pt vapor kr 스팀 jp スチーム ar steam hu gőz tr buhar th ไอน้ำ sv ånga hu gőz da damp fi höyry}
Steam {fr Vapeur de Dampf zh-hant 蒸汽棒 zh-hans 蒸汽棒 es Vapor it Vapore pt Vapor kr 스팀 jp スチーム ar Steam hu Gőz tr Buhar th ไอน้ำ sv Ånga hu Gőz da Damp fi Höyry}
stop {fr arrêter de anhalten zh-hant 停止 zh-hans 停止 es parar it interrompi pt parar kr 멈춤 jp ストップ ar stop hu stop tr Durdur th หยุด sv stopp hu stop da stop fi pysäytä}
{Tablet styles} {fr {Styles d'interface} de {Stile fürs Tablett} zh-hant 板面風格 zh-hans 板面风格 es {Estilos para la tableta} it {Stili per il tablet} pt {Estilos para o tablet} kr {태블릿 스타일} jp タブレットスタイル ar {Tablet styles} hu {Tablet stílusok} tr {Tablet temaları} th {Tablet styles} sv Skärmtema hu {Tablet stílusok} da Skærmtemaer fi Tablettityylit}
Timer {fr Minuteur de Zeitschaltuhr zh-hant 定時開關 zh-hans 定时开关 es Temporizador it Timer pt Temporizador kr {자동 on/off 설정} jp タイマー ar Timer hu Időzítő tr Zamanlayıcı th ตั้งเวลา sv Timer hu Időzítő da Timer fi Ajastin}
Update {fr {Mise à jour} de Aktualisieren zh-hant 更新 zh-hans 更新 es Actualizar it Aggiorna pt Actualizar kr 업데이트 jp アップデート ar Update hu Frissítés tr Güncelleme th Update sv Uppdatera hu Frissítés da Opdater fi Päivitä}
{Use AM/PM} {fr {Utiliser AM/PM} de {AM/PM verwenden} zh-hant 使用12小時制 zh-hans 使用12小时制 es {Usar AM/PM} it {Usa AM/PM} pt {Usar AM/PM} kr {AM/PM 사용} jp AM/PM使用 ar {Use AM/PM} hu {AM/PM használata} tr {AM/PM kullan} th {ใช้ AM/PM} sv {Använd AM/PM (12h)} hu {AM/PM használata} da {Anvend AM/PM} fi {Käytä 12 h / 24 h}}
{Use Fahrenheit} {fr {Utiliser Fahrenheit} de {Fahrenheit verwenden} zh-hant 使用華氏 zh-hans 使用华氏 es {Usar Fahrenheit} it {Usa Fahrenheit} pt {Usar Fahrenheit} kr {화씨 사용} jp 華氏を使用 ar {Use Fahrenheit} hu {Fahrenheit használata} tr {Fahrenheit kullan} th {ใช้ ฟาเรนไฮต์} sv {Använd Fahrenheit} hu {Fahrenheit használata} da {Anvend Fahrenheit} fi {Käytä fahrenheit-asteikkoa}}
Version: {fr Version: de Version: zh-hant 版本： zh-hans 版本： es Versión: it Versione: pt Versão: kr 버전: jp バージョン ar Version: hu Verzió: tr Sürüm: th Version: sv Version: hu Verzió: da Version: fi Versio:}
Water: {fr Eau: de Wasser: zh-hant 水溫： zh-hans 水温： es Agua: it Acqua: pt Água: kr 물: jp 水： ar Water: hu Víz: tr Su: th น้ำ: sv Vatten: hu Víz: da Vand: fi Vesi:}
water {fr eau de Wasser zh-hant 水 zh-hans 水 es agua it acqua pt água kr 물 jp 水 ar water hu víz tr su th น้ำ sv vatten hu víz da Vand: fi vesi}
ending {fr conclusion de Beendung zh-hant 結尾 zh-hans 结尾 es completando it conclusione pt completando kr 완료 jp 完了 ar ending hu befejezés tr bitiş th ending sv avslutar hu befejezés da afslutning fi lopettamassa}
s {fr s de s zh-hant 秒 zh-hans 秒 es s it s es s pt s kr s jp Ｓ ar s hu s tr s th s sv s hu s da s fi s}
waiting {fr attente de Warten zh-hant 等待中 zh-hans 等待中 es espera it attendi pt espera kr 대기 jp 待機中 ar waiting hu várakozás tr bekliyor th รอ sv väntar hu várakozás da vente fi odottaa}
{heating the water tank} {fr {Mise en chauffe de la chaudière} de {Erhitzen des Wasserbehälters} zh-hant 水源加熱中 zh-hans 白水加热中 es {calentamiento del tanque de agua} it {riscaldamento del serbatoio d'acqua} pt {aquecimento do tanque de água} kr {워터탱크 가열 중} jp タンクの水を加越する中 ar {heating the water tank} hu {víztartály melegítése} tr {su tankı ısıtılıyor} th {heating the water tank} sv {värmer vattentanken} hu {víztartály melegítése} da {opvarmer vandtanken} fi {Kuumentaa vesisäiliötä}}
{final heating} {fr {Stabilisation de la température} de {letzte Erhitzung} zh-hant 控溫 zh-hans 控温 es {último calentamiento} it {riscaldamento finale} pt {último aquecimento} kr {최종 가열 중} jp 最終加越 ar {final heating} hu {utolsó melegítés} tr {stabilizasyon ısıtması} th {final heating} sv {stabiliserar temperatur} hu {utolsó melegítés} da {endelig temperering} fi Loppukuumennus}
{perfecting the mix} {fr {perfectionnement du mélange} de {Perfektionierung der Mischung} zh-hant 調節水溫中 zh-hans 调节水温中 es {perfeccionando la mezcla} it {il mix perfetto} pt {aperfeiçoa da mistura} kr {설정된 온도로 믹싱 중} jp {perfecting the mix} ar {perfecting the mix} hu {keverék tökéletesítése} tr {mükemmel karışımı yakalama} th {perfecting the mix} sv {optimerar temperatur} hu {keverék tökéletesítése} da {optimerer blandingen} fi {Optimoi sekoituksen}}
(Cooling): {fr (Refroidissement): de (Abkühlung): zh-hant (冷卻中)： zh-hans (冷却中)： es (Refrigeración): it (Raffreddamento): pt (Resfriamento): kr (쿨링): jp （クーリング） ar (Cooling): hu (Hűtés): tr (Soğutma): th (Cooling): sv (Kyler): hu (Hűtés): da (Afkøling) fi (Jäähdytys):}
{Power on} {fr Allumer de Einschalten es Encender it Accendi pt Ligar zh-hant 開機 zh-hans 开机 kr 전원 jp 電源オン ar {Power on} hu Bekapcsolás tr Aç th {Power on} sv Start hu Bekapcsolás da Tænd fi {Virta päälle}}
{Hot water} {fr {Eau chaude} de Heisswasser es {Agua caliente} it {Acqua calda} pt {Água quente} zh-hant 熱水溫度 zh-hans 热水温度 kr 온수 jp お湯 ar {Hot water} hu {Forró víz} tr {Sıcak su} th น้ำร้อน sv Varmvatten hu {Forró víz} da {Varmt vand} fi {Kuuma vesi}}
WATER {fr EAU de WASSER es AGUA it ACQUA pt ÁGUA zh-hant 水 zh-hans 水 kr 물 jp 水 ar WATER hu VÍZ tr SU th น้ำ sv VATTEN hu VÍZ da VAND fi VESI}
SETTINGS {fr PARAMÈTRES de EINSTELLUNGEN es CONFIGURACIÓN it IMPOSTAZIONI pt CONFIGURAÇÕES zh-hant 設定 zh-hans 设定 kr 설정 jp 設定 ar SETTINGS hu BEÁLLÍTÁSOK tr AYARLAR th ตั้งค่า sv INSTÄLLNINGAR hu BEÁLLÍTÁSOK da INDSTILLINGER fi ASETUKSET}
Water {fr eau de Wasser zh-hant 水 zh-hans 水 es Agua it Acqua pt Água kr 물 jp 水 ar Water hu Víz tr Su th น้ำ sv Vatten hu Víz da Vand fi Vesi}
heating {fr chauffe de Erhitzung es heating it riscaldamento pt heating zh-hant 加熱中 zh-hans 加热中 kr 가열중 jp heating ar heating hu melegítés tr ısıtılıyor th heating sv värmer hu melegítés da opvamning fi Kuumentaa}
stabilising {fr stabilisation de Stabilisierung es stabilising it stabilizzazione pt stabilising zh-hant 穩定中 zh-hans 稳固中 kr {안정화 중} jp stabilising ar stabilising hu stabilizálás tr {stabilize ediliyor} th stabilising sv stabiliserar hu stabilizálás da stabilisering fi Tasapainottaa}
preinfusion {fr préinfusion de Vorinfusion es preinfusion it preinfusione pt preinfusion zh-hant 預浸 zh-hans 预浸 kr 프리인퓨전 jp preinfusion ar preinfusion hu előáztatás tr preinfüzyon th preinfusion sv preinfusion hu előáztatás da preinfusion fi esikuumennus}
pouring {fr extraction de pouring es pouring it estrazione pt pouring zh-hant 注水中 zh-hans 注水中 kr {추출 중} jp pouring ar pouring hu csapolás tr ekstraksiyon th pouring sv extraherar hu csapolás da ekstraherer fi annostaa}
Saved {fr sauvé de gespeichert es Saved it Salvato pt Saved zh-hant 儲存成功 zh-hans 储存成功 kr 저장됨 jp Saved ar Saved hu Elmentve tr Kaydedildi th Saved sv Sparad hu Elmentve da Gemt fi Tallennettu}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
"Pair" {fr "Pair" de "Pair" es "Pair" it "Pair" pt "Pair" zh-hant "Pair" zh-hans "Pair"}
"Available machines:" {fr "Available machines:" de "Available machines:" es "Available machines:" it "Available machines:" pt "Available machines:" zh-hant "Available machines:" zh-hans "Available machines:"}
"Auto stop:" {fr "Auto stop:" de "Auto stop:" es "Auto stop:" it "Auto stop:" pt "Auto stop:" zh-hant "Auto stop:" zh-hans "Auto stop:"}
