espresso_hold_time 10
preinfusion_time 5
espresso_pressure 8.8
espresso_decline_time 25
pressure_end 4
espresso_temperature 92
settings_profile_type settings_2b
flow_profile_preinfusion 4
flow_profile_preinfusion_time 5
flow_profile_hold 2.4
flow_profile_hold_time 8
flow_profile_decline 1.2
flow_profile_decline_time 17
flow_profile_minimum_pressure 4
preinfusion_flow_rate 4
profile_notes {}
water_temperature 80

