espresso_hold_time 7
preinfusion_time 12
espresso_pressure 6.1
espresso_decline_time 8
pressure_end 0.6
espresso_temperature 90.78
settings_profile_type settings_2a
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
flow_profile_hold 1.8
flow_profile_hold_time 0
flow_profile_decline 1
flow_profile_decline_time 23
flow_profile_minimum_pressure 6
preinfusion_flow_rate 4
profile_notes {}
water_temperature 80

