espresso_hold_time 30
preinfusion_time 10
espresso_pressure 8.6
espresso_decline_time 0
pressure_end 6.0
espresso_temperature 89.5
settings_profile_type settings_2a
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
flow_profile_hold 1.8
flow_profile_hold_time 0
flow_profile_decline 1
flow_profile_decline_time 23
flow_profile_minimum_pressure 6
preinfusion_flow_rate 4
profile_notes {}
water_temperature 86.0
final_desired_shot_weight 36
profile_title "Gentler but still traditional 8.4 bar"
