espresso_hold_time 20
preinfusion_time 30
espresso_pressure 9.0
espresso_decline_time 0
pressure_end 1.0
espresso_temperature 88.5
settings_profile_type settings_2b
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
flow_profile_hold 2.2
flow_profile_hold_time 0
flow_profile_decline 1.8
flow_profile_decline_time 23
flow_profile_minimum_pressure 6
preinfusion_flow_rate 3.5
profile_notes {}
water_temperature 80
final_desired_shot_weight 32
profile_title "Gentle preinfusion flow profile"
profile_language en