advanced_shot {{exit_if 0 flow 11 volume 100 max_flow_or_pressure_range 0.6 transition fast popup {} exit_flow_under 0 temperature 89.00 weight 0.0 name {fill start} pressure 1.80 sensor coffee pump pressure exit_type pressure_over exit_flow_over 6 exit_pressure_over 1.00 max_flow_or_pressure 0 exit_pressure_under 0 seconds 2} {exit_if 1 flow 11 volume 100 transition fast exit_flow_under 0 temperature 89.00 name fill pressure 1.80 sensor coffee pump pressure exit_type pressure_over exit_flow_over 6 exit_pressure_over 1.00 seconds 20 exit_pressure_under 0} {exit_if 1 flow 1.50 volume 100 transition fast exit_flow_under 0 temperature 88.50 name preinfusion pressure 2.20 sensor coffee pump pressure exit_type pressure_over exit_flow_over 6 exit_pressure_over 4 seconds 10.00 exit_pressure_under 0} {exit_if 1 volume 100 transition fast exit_flow_under 0 temperature 88.0 name rise pressure 8.00 sensor coffee pump pressure exit_type pressure_over exit_flow_over 1.50 exit_pressure_over 8.00 seconds 5.00 exit_pressure_under 0} {exit_if 1 volume 100 transition fast exit_flow_under 0 temperature 88.0 name hold pressure 8.00 sensor coffee pump pressure exit_type flow_over exit_flow_over 1.50 exit_pressure_over 11 exit_pressure_under 0 seconds 5.00} {exit_if 0 volume 100 transition smooth exit_flow_under 0 temperature 88.0 name decline pressure 2.20 sensor coffee pump pressure exit_flow_over 6 exit_pressure_over 11 seconds 58.00 exit_pressure_under 0}}
author Damian
beverage_type espresso
espresso_decline_time 35
espresso_hold_time 4
espresso_pressure 8.6
espresso_temperature 89.00
espresso_temperature_0 89.00
espresso_temperature_1 89.00
espresso_temperature_2 89.00
espresso_temperature_3 89.00
final_desired_shot_volume 36
final_desired_shot_volume_advanced 0
final_desired_shot_volume_advanced_count_start 2
final_desired_shot_weight 36
final_desired_shot_weight_advanced 42
flow_profile_decline 1.2
flow_profile_decline_time 17
flow_profile_hold 2
flow_profile_hold_time 8
flow_profile_minimum_pressure 4
flow_profile_preinfusion 4
flow_profile_preinfusion_time 5
maximum_flow 0
maximum_flow_range_advanced 0.6
maximum_flow_range_default 1.0
maximum_pressure 0
maximum_pressure_range_advanced 0.6
maximum_pressure_range_default 0.9
preinfusion_flow_rate 4
preinfusion_stop_pressure 4
preinfusion_time 20
pressure_end 6.0
profile_hide 1
profile_language en
profile_notes {Damian wrote this profile to mimic a shot Gabor Laczko recorded on a La Marzocco Leva machine using his Smart Espresso Profiler. He feels that this is a great profile for non milk drinks, it highlights flavours in a smooth balanced way, with a more creamy body than the thicker chocolatey body of the LRv2 profile. By Damian Brakel https://www.diy.brakel.com.au/}
profile_title {Damian's LM Leva}
settings_profile_type settings_2c
tank_desired_water_temperature 0
read_only 1