advanced_shot {}
author Decent
espresso_decline_time 35
espresso_hold_time 4
espresso_pressure 8.6
espresso_temperature 90.0
espresso_temperature_0 90.0
espresso_temperature_1 88.0
espresso_temperature_2 88.0
espresso_temperature_3 88.0
espresso_temperature_steps_enabled 1
final_desired_shot_volume 36
final_desired_shot_volume_advanced 0
final_desired_shot_volume_advanced_count_start 0
final_desired_shot_weight 36
final_desired_shot_weight_advanced 36
flow_profile_decline 1.2
flow_profile_decline_time 17
flow_profile_hold 2
flow_profile_hold_time 8
flow_profile_minimum_pressure 4
flow_profile_preinfusion 4
flow_profile_preinfusion_time 5
preinfusion_flow_rate 4
preinfusion_guarantee 0
preinfusion_stop_pressure 4.0
preinfusion_time 20
pressure_end 6.0
profile_hide 0
profile_language en
profile_notes {This profile is gentle on the coffee puck and not too demanding on the barista.  Produces a very acceptable espresso in a wide variety of settings.}
profile_title Default
settings_profile_type settings_2a
tank_desired_water_temperature 0
water_temperature 80
beverage_type {espresso}
profile_video_help {https://www.youtube.com/watch?v=zj-Ipuu6XGU}
