advanced_shot {}
author Decent
espresso_decline_time 20
espresso_hold_time 5
espresso_pressure 9.0
espresso_temperature 92.0
final_desired_shot_volume 36
final_desired_shot_volume_advanced 0
final_desired_shot_weight 36
final_desired_shot_weight_advanced 36
flow_profile_decline 1
flow_profile_decline_time 23
flow_profile_hold 1.8
flow_profile_hold_time 0
flow_profile_minimum_pressure 6
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
preinfusion_flow_rate 4
preinfusion_guarantee 1
preinfusion_stop_pressure 4
preinfusion_time 10
pressure_end 10.0
profile_hide 1
profile_language en
profile_notes {This high tech variation on the classic E61 9 bar shot brings out more acidity by increasing pressure towards the end of the shot.  This makes it more appropriate to drink without milk.  It will be quite thick, so adding water to make an Americano is recommended.}
profile_title {E61 classic gently up to 10 bar}
settings_profile_type settings_2a
tank_desired_water_temperature 0
water_temperature 80
beverage_type {espresso}
read_only 1