advanced_shot {{flow 5.0 exit_if 0 volume 75 max_flow_or_pressure_range 1.0 transition fast popup {} exit_flow_under 0 temperature 94.0 weight 0 name Prewet pressure 9.0 pump flow sensor water exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 5.0 seconds 15 exit_pressure_under 0} {flow 0 exit_if 0 volume 75 max_flow_or_pressure_range 1.0 transition fast popup {} exit_flow_under 0 temperature 94.0 weight 0 name Bloom pressure 9.0 sensor water pump flow exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 exit_pressure_under 0 seconds 30} {flow 1.1 exit_if 0 volume 200 max_flow_or_pressure_range 1.0 transition fast popup {} exit_flow_under 0 temperature 92.0 weight 0 name {Step 1a} pressure 9.0 sensor water pump flow exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 exit_pressure_under 0 seconds 30} {flow 1.1 exit_if 0 volume 200 max_flow_or_pressure_range 1.0 transition fast popup {Swirl now*} exit_flow_under 0 temperature 92.0 weight 0 name {Step 1b} pressure 9.0 pump flow sensor water exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 seconds 30 exit_pressure_under 0} {flow 1.1 exit_if 0 volume 200 max_flow_or_pressure_range 1.0 transition fast popup {} exit_flow_under 0 temperature 90.0 weight 0 name {Step 2} pressure 9.0 sensor water pump flow exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 exit_pressure_under 0 seconds 60} {flow 1.1 exit_if 0 volume 200 max_flow_or_pressure_range 1.0 transition fast popup {} exit_flow_under 0 temperature 88.0 weight 0 name {Step 3} pressure 9.0 sensor water pump flow exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 exit_pressure_under 0 seconds 100} {flow 0 exit_if 0 volume 200 max_flow_or_pressure_range 1.0 transition fast popup {Wait for all coffee to draw down} exit_flow_under 0 temperature 88.0 weight 0 name Drawdown pressure 9.0 pump flow sensor water exit_flow_over 6 exit_pressure_over 0 max_flow_or_pressure 0 seconds 10 exit_pressure_under 0}}
espresso_temperature_steps_enabled 0
author Decent
espresso_hold_time 10
preinfusion_time 20
espresso_pressure 8.5
espresso_decline_time 40
pressure_end 2.0
espresso_temperature 94.0
espresso_temperature_0 94.0
espresso_temperature_1 94.0
espresso_temperature_2 94.0
espresso_temperature_3 94.0
settings_profile_type settings_2c
flow_profile_preinfusion 4
flow_profile_preinfusion_time 5
flow_profile_hold 2
flow_profile_hold_time 8
flow_profile_decline 1.2
flow_profile_decline_time 17
flow_profile_minimum_pressure 4
preinfusion_flow_rate 4
profile_notes {Set your grinder as coarsely as it can be set (11am setting on a Niche Zero).  Center a 58.5mm filter paper in the bottom of a Filter3 basket. Wet it with Flush water. Add 22 grams of coffee and shake to level the grounds.  Gently lock the portafilter in.  Place a cup, tap the COFFEE icon on the Group Head to start.  Optional: 30 seconds into the extraction, unlock the portafilter, swirl and check for 2cm-4cm of water on the grounds.  Adjust the grind if necessary for next time: finer if you saw not enough water, coarser if there was too much water on the grounds.  If water comes out of the holes at the top of the basket, your grind is too fine.}
final_desired_shot_volume 36
final_desired_shot_weight 0.0
final_desired_shot_weight_advanced 0.0
tank_desired_water_temperature 0
final_desired_shot_volume_advanced 0
profile_title Filter3
profile_language en
preinfusion_stop_pressure 4.0
profile_hide 1
final_desired_shot_volume_advanced_count_start 2
beverage_type filter
maximum_pressure 0
maximum_pressure_range_advanced 0.9
maximum_flow_range_advanced 1.0
maximum_flow 4.0
maximum_pressure_range_default 0.9
maximum_flow_range_default 1.0

