advanced_shot {}
author Decent
beverage_type espresso
espresso_decline_time 2
espresso_hold_time 31
espresso_pressure 8.4
espresso_temperature 89.5
espresso_temperature_0 89.5
espresso_temperature_1 89.5
espresso_temperature_2 89.5
espresso_temperature_3 89.5
espresso_temperature_steps_enabled 1
final_desired_shot_volume 37
final_desired_shot_volume_advanced 135
final_desired_shot_volume_advanced_count_start 0
final_desired_shot_weight 36
final_desired_shot_weight_advanced 135
flow_profile_decline 1
flow_profile_decline_time 23
flow_profile_hold 1.8
flow_profile_hold_time 0
flow_profile_minimum_pressure 6
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
maximum_flow 0
maximum_flow_range_advanced 0.6
maximum_flow_range_default 1.0
maximum_pressure 0
maximum_pressure_range_advanced 0.6
maximum_pressure_range_default 0.9
preinfusion_flow_rate 4
preinfusion_stop_pressure 4.0
preinfusion_time 10
pressure_end 6.0
profile_hide 1
profile_language en
profile_notes {Professional baristas worldwide have found that slightly lowering the pressure from 9 bar down to 8.4 produces great espresso more often.  The gentler pressure still produces traditional flavors but requires less perfect preparation skills from the barista.}
profile_title {Gentler but still traditional 8.4 bar}
read_only 1
settings_profile_type settings_2a
tank_desired_water_temperature 0

