advanced_shot {}
author Decent
beverage_type espresso
espresso_decline_time 0
espresso_hold_time 21
espresso_pressure 9.0
espresso_temperature 92.0
espresso_temperature_0 92.0
espresso_temperature_1 92.0
espresso_temperature_2 92.0
espresso_temperature_3 92.0
espresso_temperature_steps_enabled 1
final_desired_shot_volume 37
final_desired_shot_volume_advanced 135
final_desired_shot_volume_advanced_count_start 0
final_desired_shot_weight 36
final_desired_shot_weight_advanced 135
flow_profile_decline 1.8
flow_profile_decline_time 23
flow_profile_hold 2.2
flow_profile_hold_time 0
flow_profile_minimum_pressure 6
flow_profile_preinfusion 4.2
flow_profile_preinfusion_time 6
maximum_flow 0
maximum_flow_range_advanced 0.6
maximum_flow_range_default 1.0
maximum_pressure 0
maximum_pressure_range_advanced 0.6
maximum_pressure_range_default 0.9
preinfusion_flow_rate 3.5
preinfusion_stop_pressure 4.0
preinfusion_time 30
pressure_end 1.0
profile_hide 1
profile_language en
profile_notes {Created by a famously innovative Seattle-based espresso machine manufacturer, this technique works well with aromatic, lightly roasted coffee beans.}
profile_title {Gentle preinfusion flow profile}
read_only 1
settings_profile_type settings_2b
tank_desired_water_temperature 0

