advanced_shot {}
author Decent
beverage_type espresso
espresso_decline_time 30
espresso_hold_time 16
espresso_pressure 6.0
espresso_temperature 88.0
espresso_temperature_0 88.0
espresso_temperature_1 88.0
espresso_temperature_2 88.0
espresso_temperature_3 88.0
final_desired_shot_volume 36
final_desired_shot_volume_advanced 135
final_desired_shot_volume_advanced_count_start 0
final_desired_shot_weight 36
final_desired_shot_weight_advanced 135
flow_profile_decline 1.2
flow_profile_decline_time 17
flow_profile_hold 2
flow_profile_hold_time 8
flow_profile_minimum_pressure 4
flow_profile_preinfusion 4
flow_profile_preinfusion_time 5
maximum_flow 4.0
maximum_flow_range_advanced 0.6
maximum_flow_range_default 1.0
maximum_pressure 0
maximum_pressure_range_advanced 0.6
maximum_pressure_range_default 0.9
preinfusion_flow_rate 4
preinfusion_stop_pressure 4.0
preinfusion_time 20
pressure_end 4.0
profile_hide 0
profile_language en
profile_notes {This is a very easy espresso to successfully make and is suggested if you are having difficulty making good drinks.  The pressure rises to only 6 bar and then slowly descends to 4 bar.  The resulting espresso should be free of channeling, have low acidity and quite pleasant to drink straight or with milk.}
profile_title {Gentle and sweet}
read_only 1
settings_profile_type settings_2a
tank_desired_water_temperature 0
water_temperature 80

